# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c747e557caddc9807f55dd4a57c511216409f7589a4963c2eb8c5118a41a76f7956b2f8fed443311f221057e7b86e48ae558c639037ed9ab933508650eb44a66

test:
  secret_key_base: 52bf180388074a2604efee0dd32ebdd939a8cfa25ba37901d2f38100be70d581078b95728505235891b079fa3822c3077ada6825923e63952eb018a896597d03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
